import axios from "axios";

const URL = "http://localhost:5000";
const API_BASE_URL = `${URL}/api/trivia`;

/**
 * Represents a trivia question.
 */
interface Question {
  /** The unique identifier for the question. */
  id: number;
  /** The category to which the question belongs. */
  category: string;
  /** The text of the question. */
  question: string;
  /** The list of possible answer choices. */
  options: string[];
  /** The correct answer for the question. */
  answer: string;
}

/**
 * API service for managing trivia questions.
 * Provides methods for creating, reading, updating, and deleting questions.
 */
const apiServices = {
  /**
   * Creates a new trivia question within a specific category.
   * 
   * @param category - The category in which the question will be added.
   * @param questionData - The question details, excluding the `id` (generated by the server).
   * @returns A promise that resolves to the newly created `Question` object.
   * @throws Will throw an error if the API request fails.
   */
  async createQuestion(
    category: string,
    questionData: Omit<Question, "id">
  ): Promise<Question> {
    try {
      const response = await axios.post<Question>(
        `${API_BASE_URL}/categories/${category}`,
        questionData
      );
      return response.data;
    } catch (error) {
      console.error(`Error creating question in category ${category}:`, error);
      throw error;
    }
  },

  /**
   * Retrieves a list of all available trivia categories.
   * 
   * @returns A promise that resolves to an array of category names.
   * @throws Will throw an error if the API request fails.
   */
  async getAllCategories(): Promise<string[]> {
    try {
      const response = await axios.get<string[]>(`${API_BASE_URL}/categories`);
      return response.data;
    } catch (error) {
      console.error("Error fetching categories:", error);
      throw error;
    }
  },

  /**
   * Retrieves all trivia questions within a given category.
   * 
   * @param category - The category from which to fetch questions.
   * @returns A promise that resolves to an array of `Question` objects.
   * @throws Will throw an error if the API request fails.
   */
  async getAllQuestions(category: string): Promise<Question[]> {
    try {
      const response = await axios.get<Question[]>(
        `${API_BASE_URL}/categories/${category}`
      );
      return response.data;
    } catch (error) {
      console.error(`Error fetching questions for category ${category}:`, error);
      throw error;
    }
  },

  /**
   * Retrieves a specific trivia question by its ID within a given category.
   * 
   * @param category - The category of the question.
   * @param id - The unique ID of the question.
   * @returns A promise that resolves to the `Question` object.
   * @throws Will throw an error if the API request fails.
   */
  async getQuestionById(category: string, id: number): Promise<Question> {
    try {
      const response = await axios.get<Question>(
        `${API_BASE_URL}/categories/${category}/${id}`
      );
      return response.data;
    } catch (error) {
      console.error(`Error fetching question ${id} in category ${category}:`, error);
      throw error;
    }
  },

  /**
   * Updates an existing trivia question.
   * 
   * @param category - The category of the question.
   * @param id - The unique ID of the question to be updated.
   * @param updatedData - The updated question data (partial object).
   * @returns A promise that resolves to the updated `Question` object.
   * @throws Will throw an error if the API request fails.
   */
  async updateQuestion(
    category: string,
    id: number,
    updatedData: Partial<Question>
  ): Promise<Question> {
    try {
      const response = await axios.patch<Question>(
        `${API_BASE_URL}/categories/${category}/${id}`,
        updatedData
      );
      return response.data;
    } catch (error) {
      console.error(`Error updating question ${id} in category ${category}:`, error);
      throw error;
    }
  },

  /**
   * Deletes a trivia question by its ID within a given category.
   * 
   * @param category - The category of the question.
   * @param id - The unique ID of the question to be deleted.
   * @returns A promise that resolves to a success message.
   * @throws Will throw an error if the API request fails.
   */
  async deleteQuestion(category: string, id: number): Promise<{ message: string }> {
    try {
      const response = await axios.delete<{ message: string }>(
        `${API_BASE_URL}/categories/${category}/${id}`
      );
      return response.data;
    } catch (error) {
      console.error(`Error deleting question ${id} in category ${category}:`, error);
      throw error;
    }
  },
};

export default apiServices;
